// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: protos/hotel/hotel.proto

package hotelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckHotelIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CheckHotelIDRequest) Reset() {
	*x = CheckHotelIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHotelIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHotelIDRequest) ProtoMessage() {}

func (x *CheckHotelIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHotelIDRequest.ProtoReflect.Descriptor instead.
func (*CheckHotelIDRequest) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *CheckHotelIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckHotelIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *CheckHotelIDResponse) Reset() {
	*x = CheckHotelIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHotelIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHotelIDResponse) ProtoMessage() {}

func (x *CheckHotelIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHotelIDResponse.ProtoReflect.Descriptor instead.
func (*CheckHotelIDResponse) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *CheckHotelIDResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type AddHotelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID int32 `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
}

func (x *AddHotelResponse) Reset() {
	*x = AddHotelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHotelResponse) ProtoMessage() {}

func (x *AddHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHotelResponse.ProtoReflect.Descriptor instead.
func (*AddHotelResponse) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *AddHotelResponse) GetHotelID() int32 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

type GetHotelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHotelsRequest) Reset() {
	*x = GetHotelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsRequest) ProtoMessage() {}

func (x *GetHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetHotelsRequest) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{3}
}

type GetHotelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hotels []*Hotel `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
}

func (x *GetHotelsResponse) Reset() {
	*x = GetHotelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsResponse) ProtoMessage() {}

func (x *GetHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsResponse.ProtoReflect.Descriptor instead.
func (*GetHotelsResponse) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{4}
}

func (x *GetHotelsResponse) GetHotels() []*Hotel {
	if x != nil {
		return x.Hotels
	}
	return nil
}

type GetHotelDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID string `protobuf:"bytes,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
}

func (x *GetHotelDetailsRequest) Reset() {
	*x = GetHotelDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelDetailsRequest) ProtoMessage() {}

func (x *GetHotelDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetHotelDetailsRequest) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{5}
}

func (x *GetHotelDetailsRequest) GetHotelID() string {
	if x != nil {
		return x.HotelID
	}
	return ""
}

type GetHotelDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hotel *Hotel `protobuf:"bytes,1,opt,name=hotel,proto3" json:"hotel,omitempty"`
}

func (x *GetHotelDetailsResponse) Reset() {
	*x = GetHotelDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelDetailsResponse) ProtoMessage() {}

func (x *GetHotelDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetHotelDetailsResponse) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{6}
}

func (x *GetHotelDetailsResponse) GetHotel() *Hotel {
	if x != nil {
		return x.Hotel
	}
	return nil
}

type CheckRoomAvailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID string `protobuf:"bytes,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
}

func (x *CheckRoomAvailabilityRequest) Reset() {
	*x = CheckRoomAvailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRoomAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomAvailabilityRequest) ProtoMessage() {}

func (x *CheckRoomAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckRoomAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{7}
}

func (x *CheckRoomAvailabilityRequest) GetHotelID() string {
	if x != nil {
		return x.HotelID
	}
	return ""
}

type CheckRoomAvailabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomAvailabilities []*RoomAvailability `protobuf:"bytes,1,rep,name=roomAvailabilities,proto3" json:"roomAvailabilities,omitempty"`
}

func (x *CheckRoomAvailabilityResponse) Reset() {
	*x = CheckRoomAvailabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRoomAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomAvailabilityResponse) ProtoMessage() {}

func (x *CheckRoomAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckRoomAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{8}
}

func (x *CheckRoomAvailabilityResponse) GetRoomAvailabilities() []*RoomAvailability {
	if x != nil {
		return x.RoomAvailabilities
	}
	return nil
}

type Hotel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID  string  `protobuf:"bytes,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location string  `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Rating   float64 `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Address  string  `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Rooms    []*Room `protobuf:"bytes,6,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{9}
}

func (x *Hotel) GetHotelID() string {
	if x != nil {
		return x.HotelID
	}
	return ""
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Hotel) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Hotel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Hotel) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType      string  `protobuf:"bytes,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	PricePerNight float64 `protobuf:"fixed64,2,opt,name=pricePerNight,proto3" json:"pricePerNight,omitempty"`
	Availability  bool    `protobuf:"varint,3,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{10}
}

func (x *Room) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *Room) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *Room) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type RoomAvailability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType       string `protobuf:"bytes,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	AvailableRooms int32  `protobuf:"varint,2,opt,name=availableRooms,proto3" json:"availableRooms,omitempty"`
}

func (x *RoomAvailability) Reset() {
	*x = RoomAvailability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hotel_hotel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAvailability) ProtoMessage() {}

func (x *RoomAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hotel_hotel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAvailability.ProtoReflect.Descriptor instead.
func (*RoomAvailability) Descriptor() ([]byte, []int) {
	return file_protos_hotel_hotel_proto_rawDescGZIP(), []int{11}
}

func (x *RoomAvailability) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *RoomAvailability) GetAvailableRooms() int32 {
	if x != nil {
		return x.AvailableRooms
	}
	return 0
}

var File_protos_hotel_hotel_proto protoreflect.FileDescriptor

var file_protos_hotel_hotel_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2f, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x2c, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22,
	0x2c, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x12, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x33, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x06,
	0x68, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x22, 0x32, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x37, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x05, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x22, 0x38, 0x0a, 0x1c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x62, 0x0a,
	0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41,
	0x0a, 0x12, 0x72, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x12, 0x72,
	0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x22, 0xa0, 0x01, 0x0a, 0x05, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x6c, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x22, 0x56, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x32, 0xc4, 0x02, 0x0a, 0x0c, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x06, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x1a,
	0x11, 0x2e, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x12,
	0x11, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x15,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f,
	0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x49, 0x44, 0x12, 0x14, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_hotel_hotel_proto_rawDescOnce sync.Once
	file_protos_hotel_hotel_proto_rawDescData = file_protos_hotel_hotel_proto_rawDesc
)

func file_protos_hotel_hotel_proto_rawDescGZIP() []byte {
	file_protos_hotel_hotel_proto_rawDescOnce.Do(func() {
		file_protos_hotel_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_hotel_hotel_proto_rawDescData)
	})
	return file_protos_hotel_hotel_proto_rawDescData
}

var file_protos_hotel_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protos_hotel_hotel_proto_goTypes = []any{
	(*CheckHotelIDRequest)(nil),           // 0: CheckHotelIDRequest
	(*CheckHotelIDResponse)(nil),          // 1: CheckHotelIDResponse
	(*AddHotelResponse)(nil),              // 2: AddHotelResponse
	(*GetHotelsRequest)(nil),              // 3: GetHotelsRequest
	(*GetHotelsResponse)(nil),             // 4: GetHotelsResponse
	(*GetHotelDetailsRequest)(nil),        // 5: GetHotelDetailsRequest
	(*GetHotelDetailsResponse)(nil),       // 6: GetHotelDetailsResponse
	(*CheckRoomAvailabilityRequest)(nil),  // 7: CheckRoomAvailabilityRequest
	(*CheckRoomAvailabilityResponse)(nil), // 8: CheckRoomAvailabilityResponse
	(*Hotel)(nil),                         // 9: Hotel
	(*Room)(nil),                          // 10: Room
	(*RoomAvailability)(nil),              // 11: RoomAvailability
}
var file_protos_hotel_hotel_proto_depIdxs = []int32{
	9,  // 0: GetHotelsResponse.hotels:type_name -> Hotel
	9,  // 1: GetHotelDetailsResponse.hotel:type_name -> Hotel
	11, // 2: CheckRoomAvailabilityResponse.roomAvailabilities:type_name -> RoomAvailability
	10, // 3: Hotel.rooms:type_name -> Room
	9,  // 4: HotelService.AddHotel:input_type -> Hotel
	3,  // 5: HotelService.GetHotels:input_type -> GetHotelsRequest
	5,  // 6: HotelService.GetHotelDetails:input_type -> GetHotelDetailsRequest
	7,  // 7: HotelService.CheckRoomAvailability:input_type -> CheckRoomAvailabilityRequest
	0,  // 8: HotelService.CheckHotelID:input_type -> CheckHotelIDRequest
	2,  // 9: HotelService.AddHotel:output_type -> AddHotelResponse
	4,  // 10: HotelService.GetHotels:output_type -> GetHotelsResponse
	6,  // 11: HotelService.GetHotelDetails:output_type -> GetHotelDetailsResponse
	8,  // 12: HotelService.CheckRoomAvailability:output_type -> CheckRoomAvailabilityResponse
	1,  // 13: HotelService.CheckHotelID:output_type -> CheckHotelIDResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_hotel_hotel_proto_init() }
func file_protos_hotel_hotel_proto_init() {
	if File_protos_hotel_hotel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_hotel_hotel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CheckHotelIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CheckHotelIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddHotelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetHotelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetHotelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetHotelDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetHotelDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CheckRoomAvailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CheckRoomAvailabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Hotel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_hotel_hotel_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RoomAvailability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_hotel_hotel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_hotel_hotel_proto_goTypes,
		DependencyIndexes: file_protos_hotel_hotel_proto_depIdxs,
		MessageInfos:      file_protos_hotel_hotel_proto_msgTypes,
	}.Build()
	File_protos_hotel_hotel_proto = out.File
	file_protos_hotel_hotel_proto_rawDesc = nil
	file_protos_hotel_hotel_proto_goTypes = nil
	file_protos_hotel_hotel_proto_depIdxs = nil
}
